# Utilisez une image de base officielle Python, par exemple Python 3.10
FROM python:3.12.1

RUN mkdir /app
# Définissez le répertoire de travail dans le conteneur
WORKDIR /app

CMD ["python", "./app.py"]